// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	saveTasks: (items: Task[]) => __TAURI_INVOKE<void>("save_tasks", { items }),
	loadTasks: () => __TAURI_INVOKE<Task[]>("load_tasks"),
};

/* Types */
export type Task = {
	id: number,
	text: string,
	completed: boolean,
	is_suspended: boolean,
	vruntime: number,
	priority: number,
	tags: string[] | null,
};

