// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	testFunction: (items: Task[]) => __TAURI_INVOKE<void>("test_function", { items }),
};

/* Types */
export type Task = {
	id: number,
	text: string,
	completed: boolean,
	is_suspended: boolean,
	vruntime: number,
	priority: number,
};

