// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	saveTasks: (items: Task[]) => __TAURI_INVOKE<void>("save_tasks", { items }),
	loadTasks: () => __TAURI_INVOKE<Task[]>("load_tasks"),
	saveWorkspaces: (items: Workspace[]) => __TAURI_INVOKE<void>("save_workspaces", { items }),
	loadWorkspaces: () => __TAURI_INVOKE<Workspace[]>("load_workspaces"),
};

/* Types */
export type Task = {
	id: number,
	text: string,
	extendedText: string,
	completed: boolean,
	isSuspended: boolean,
	vruntime: number,
	priority: number,
	weight: number | null,
	tags: string[] | null,
};

export type Workspace = {
	id: number,
	name: string,
	iconId: string | null,
	filterQuery: string,
};

